# Generated by Django 5.2 on 2025-04-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='titulo',
            new_name='tarea',
        ),
    ]
